// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zympnpibhohnxsnbxtaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5bXBucGliaG9obnhzbmJ4dGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODExNDgsImV4cCI6MjA2NTI1NzE0OH0.Otw66MX1RN89oMO6dSWuhz1KC-GWMhEAaeAwcPZ86nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);